server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080

jerseyClient:
  gzipEnabled: false
  gzipEnabledForRequests: false
  chunkedEncodingEnabled: false
  timeout: 30000ms

logging:
  level: INFO

name: ${MY_NAME}