apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: java-template-secrets
  namespace: production
spec:
  backendType: gcpSecretsManager
  projectId: kudi-209818
  data:
    - key: production-java-template-my_name
      name: MY_NAME
      version: latest
