apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: __SERVICE_NAME__-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       __SERVICE_NAME__
  updatePolicy:
    updateMode: "__VPA_UPDATE_MODE__"
  resourcePolicy:
    containerPolicies:
    - containerName: __SERVICE_NAME__
      minAllowed:
        cpu: 20m
        memory: 50Mi
      maxAllowed:
        cpu: 1200m
        memory: 4Gi 
